[2023-07-17 07:30:17,269] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sample_connection.python_callable scheduled__2023-07-15T23:00:00+00:00 [queued]>
[2023-07-17 07:30:17,277] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sample_connection.python_callable scheduled__2023-07-15T23:00:00+00:00 [queued]>
[2023-07-17 07:30:17,278] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-17 07:30:17,278] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-17 07:30:17,278] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-17 07:30:17,293] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): python_callable> on 2023-07-15 23:00:00+00:00
[2023-07-17 07:30:17,299] {standard_task_runner.py:52} INFO - Started process 1483 to run task
[2023-07-17 07:30:17,301] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sample_connection', 'python_callable', 'scheduled__2023-07-15T23:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/sample_connection.py', '--cfg-path', '/tmp/tmpoj6yt7ly', '--error-file', '/tmp/tmpuoxrwfuf']
[2023-07-17 07:30:17,302] {standard_task_runner.py:80} INFO - Job 26: Subtask python_callable
[2023-07-17 07:30:17,365] {task_command.py:369} INFO - Running <TaskInstance: sample_connection.python_callable scheduled__2023-07-15T23:00:00+00:00 [running]> on host 938e71f84edd
[2023-07-17 07:30:17,451] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sample_connection
AIRFLOW_CTX_TASK_ID=python_callable
AIRFLOW_CTX_EXECUTION_DATE=2023-07-15T23:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-15T23:00:00+00:00
[2023-07-17 07:30:17,461] {base.py:68} INFO - Using connection ID 'pg-conn' for task execution.
[2023-07-17 07:32:28,136] {logging_mixin.py:115} INFO - [INFO] Can't connect PostgreSQL postgres
[2023-07-17 07:32:28,136] {logging_mixin.py:115} INFO - connection to server at "103.150.197.96", port 5431 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?
[2023-07-17 07:32:28,137] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sample_connection.py", line 35, in python_callable
    conn, engine = psql_conn(conf, 'postgres')
TypeError: cannot unpack non-iterable NoneType object
[2023-07-17 07:32:28,147] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=sample_connection, task_id=python_callable, execution_date=20230715T230000, start_date=20230717T073017, end_date=20230717T073228
[2023-07-17 07:32:28,161] {standard_task_runner.py:97} ERROR - Failed to execute job 26 for task python_callable (cannot unpack non-iterable NoneType object; 1483)
[2023-07-17 07:32:28,193] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-17 07:32:28,220] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
