[2023-06-24 04:18:16,284] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sample_connection.python_callable manual__2023-06-24T04:18:14.908542+00:00 [queued]>
[2023-06-24 04:18:16,293] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: sample_connection.python_callable manual__2023-06-24T04:18:14.908542+00:00 [queued]>
[2023-06-24 04:18:16,294] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-06-24 04:18:16,294] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-06-24 04:18:16,294] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-06-24 04:18:16,309] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): python_callable> on 2023-06-24 04:18:14.908542+00:00
[2023-06-24 04:18:16,313] {standard_task_runner.py:52} INFO - Started process 529 to run task
[2023-06-24 04:18:16,316] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'sample_connection', 'python_callable', 'manual__2023-06-24T04:18:14.908542+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/sample_connection.py', '--cfg-path', '/tmp/tmpbhgtq0ok', '--error-file', '/tmp/tmpa9p4iqh7']
[2023-06-24 04:18:16,317] {standard_task_runner.py:80} INFO - Job 4: Subtask python_callable
[2023-06-24 04:18:16,367] {task_command.py:369} INFO - Running <TaskInstance: sample_connection.python_callable manual__2023-06-24T04:18:14.908542+00:00 [running]> on host 36e9483e82ad
[2023-06-24 04:18:16,471] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sample_connection
AIRFLOW_CTX_TASK_ID=python_callable
AIRFLOW_CTX_EXECUTION_DATE=2023-06-24T04:18:14.908542+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-24T04:18:14.908542+00:00
[2023-06-24 04:18:16,483] {base.py:68} INFO - Using connection ID 'pg-conn' for task execution.
[2023-06-24 04:18:16,489] {logging_mixin.py:115} INFO - [INFO] Can't connect PostgreSQL postgres
[2023-06-24 04:18:16,490] {logging_mixin.py:115} INFO - connection to server at "103.105.197.96", port 5431 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2023-06-24 04:18:16,490] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sample_connection.py", line 35, in python_callable
    conn, engine = psql_conn(conf, 'postgres')
TypeError: cannot unpack non-iterable NoneType object
[2023-06-24 04:18:16,500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=sample_connection, task_id=python_callable, execution_date=20230624T041814, start_date=20230624T041816, end_date=20230624T041816
[2023-06-24 04:18:16,514] {standard_task_runner.py:97} ERROR - Failed to execute job 4 for task python_callable (cannot unpack non-iterable NoneType object; 529)
[2023-06-24 04:18:16,528] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-24 04:18:16,563] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
