[2023-07-17 07:50:50,945] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_airflow_task.my_task scheduled__2023-03-02T00:00:00+00:00 [queued]>
[2023-07-17 07:50:50,958] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_airflow_task.my_task scheduled__2023-03-02T00:00:00+00:00 [queued]>
[2023-07-17 07:50:50,958] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-07-17 07:50:50,958] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-07-17 07:50:50,958] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-07-17 07:50:50,988] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): my_task> on 2023-03-02 00:00:00+00:00
[2023-07-17 07:50:50,994] {standard_task_runner.py:52} INFO - Started process 2557 to run task
[2023-07-17 07:50:51,004] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_***_task', 'my_task', 'scheduled__2023-03-02T00:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/read_csv.py', '--cfg-path', '/tmp/tmpnrjx19id', '--error-file', '/tmp/tmp4xg_e8n8']
[2023-07-17 07:50:51,005] {standard_task_runner.py:80} INFO - Job 88: Subtask my_task
[2023-07-17 07:50:51,079] {task_command.py:369} INFO - Running <TaskInstance: my_airflow_task.my_task scheduled__2023-03-02T00:00:00+00:00 [running]> on host 938e71f84edd
[2023-07-17 07:50:51,242] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_***_task
AIRFLOW_CTX_TASK_ID=my_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-02T00:00:00+00:00
[2023-07-17 07:50:51,245] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/read_csv.py", line 10, in read_csv
    df = pd.read_csv('/home/andhika/airflow_v2/dags/datacovid19.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/home/andhika/airflow_v2/dags/datacovid19.csv'
[2023-07-17 07:50:51,260] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_***_task, task_id=my_task, execution_date=20230302T000000, start_date=20230717T075050, end_date=20230717T075051
[2023-07-17 07:50:51,279] {standard_task_runner.py:97} ERROR - Failed to execute job 88 for task my_task ([Errno 2] No such file or directory: '/home/andhika/airflow_v2/dags/datacovid19.csv'; 2557)
[2023-07-17 07:50:51,300] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-17 07:50:51,372] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
